# Generated by Django 2.0.5 on 2018-06-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('file', models.CharField(max_length=250)),
            ],
        ),
    ]
